languages:
   Ruby: false
   JavaScript: true
   Python: false
   PHP: false
exclude_paths:
- "meta/*"
- "mink-plugin/font-awesome-4.0.3/*"
- "mink-plugin/highchartsdata.js"
- "mink-plugin/images/*"
- "mink-plugin/jquery.miller.js/*"
- "mink-plugin/js/jquery-3.4.1.min.js"