name: Screenshot GUI

on:
  - push

jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: npm test

  build:
    runs-on: macos-latest
    name: Setup Chrome
    steps:
      - name: Get latest Mink source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: browser-actions/setup-chrome@v1
      - run: Chromium --version
      - name: Report Python version
        run: file `which python3`
      - name: Create venv to isolate Python dependencies
        run: |
          python3 -m venv mink
          source mink/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install screenshot utility
        run: python3 -m pip install screenshot
      - name: Launch Chrome
        run: Chromium
      - name: Take screenshot of Chrome
        run: screenshot Chromium --filename chrome.png --shadow
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: chrome.png
          path: chrome*.pjng
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome


