name: Screenshot GUI

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    name: Setup Chrome
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Report Python version
        run: file `which python3`
      - name: Install screenshot utility
        run: python3 -m pip install screenshot
      - name: Launch Chrome
        run: chrome
      - name: Take screenshot of Chrome
        run: screenshot chrome --filename chrome.png --shadow
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: chrome.png
          path: chrome*.pjng
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome
    
