name: Screenshot GUI

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    name: Setup Chrome
    steps:
      - name: Get latest Mink source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: browser-actions/setup-chrome@v1
      - run: |
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - name: Report Python version
        run: file `which python3`
      - name: Create venv to isolate Python dependencies
        run: |
          python3 -m venv mink
          source mink/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install screenshot utility
        run: python3 -m pip install screenshot
      - name: Launch Chrome
        run: ${{ steps.setup-chrome.outputs.chrome-path }}
      - name: Take screenshot of Chrome
        run: screenshot Chromium --filename chrome.png --shadow
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: chrome.png
          path: chrome*.pjng
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome
    
